# Site settings
title: Lucius's Blog
url: "https://lucius0.github.io"
baseurl: ""
timezone: Asia/Shanghai

encoding: "utf-8"
description: >
 stay hungry, stay foolish...

# Your information
email: lucius3433433@gmail.com
author: lucius
avatar: "/images/avatar.jpg"
profile:  stay hungry, stay foolish...

# Comment Service
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
duoshuo_shortname: lucius0  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 # - jekyll-gist
 # - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

# highlighter: rouge
markdown: kramdown

# kramdown:
#   input: GFM
#   syntax_highlighter: rouge